### ISSUE TITLE
cannot find RaXML results even though is in path

### ISSUE THREAD

**Issue by elipapa** [dgaston/FunDi#1]
When I try to run FunDI, I hit the following error

``` sh
perl FunDi.pl -t uniprot-meropsC12.shortnames.nw -a uniprot-meropsC12.shortnames.afasta -s subtree.def -P qmmraxml
Retrieving subtree definitions from subtree.def...
Optimizing branch lengths of input user tree using QmmRAxML
Executing QmmRAxML with following command-line: -s uniprot-meropsC12.shortnames.afasta -t uniprot-meropsC12.shortnames.nw -n uniprot-meropsC12.shortnames.afasta_optimized.out -m PROTGAMMALG -u 9componentsDirichlet_LG.dat -f e
Could not find RAxML_result.uniprot-meropsC12.shortnames.afasta_optimized.out. Exiting...
```

It appears `qmmraxml` does not write the results to disk. The program is in the path and I can call it from the command line.

Any clues?

**Comment by dgaston** [comment]
Hi Elipapa, 
Yes it does sound like qmmraxml may not be executing correctly. If you run just the qmmraxml command that FunDi outputs what do you get?

**Comment by elipapa** [comment]
Thanks for the quick reply @dgaston !
Running on its own, it appears it has some trouble in parsing the multifasta?

```
qmmraxmlHPC -s uniprot-meropsC12.shortnames.afasta -t uniprot-meropsC12.shortnames.nw -n uniprot-meropsC12.shortnames.afasta_optimized.out -m PROTGAMMALG -u 9componentsDirichlet_LG.dat -f e
ERROR: Problem reading number of species and sites
```

**Comment by dgaston** [comment]
Ah I see the problem now. Qmmraxml only reads phylip format files. FunDi has a parser and will convert standard fasta to phylip on input but it isn't a very sophisticated detection mechanism and just looks for standard fasta file extensions people use like .fasta and .fst so where yours is .afasta it wouldn't try and convert it. So if you change the file name, and assuming it is a standard fasta file it should be able to convert it to phylip for you. Otherwise if you run a conversion program first and give the phylip file to FunDi it should work

**Comment by dgaston** [comment]
Closing for now, please re-open if you still have issues with the file conversion.
